#!/bin/bash
mulog=$(mesinssh)
date=$(date)
data=( `cat /etc/passwd | grep home | cut -d ' ' -f 1 | cut -d : -f 1`);
for user in "${data[@]}"
do
iplimit=$(cat /etc/funny/limit/ssh/ip/$user)
cekcek=$(echo -e "$mulog" | grep $user | wc -l);
if [[ $cekcek -gt $iplimit ]]; then
userdel -f -r $user
nais=3
echo -e "$waktu\nRemoved User: $user Login: $cekcek IP Max: $ip IP \n" >> /etc/funny/log/ssh/ssh.log
else
echo > /dev/null
fi
sleep 0.1
done
if [[ $nais -gt 1 ]]; then
else
echo > /dev/null
fi
